module Pages.Game exposing (view)

import Html exposing (..)
import Html.Attributes as A

view : List (Html msg)
view =
  [ article [ A.class "main content profile" ]
    [ div [ A.class "profile-info" ]
      [ h1 [ A.class "profile-name" ]
        [ a [ A.class "link", A.href "./game.html" ]
          [ text "Pistolita High School Elimination 2020" ]
        , span [ A.class "flex" ]
          []
        , a [ A.class "icon-btn settings-btn", A.href "./game-settings.html" ]
          [ text "Settings" ]
        , button [ A.class "button join-btn" ]
          [ text "Join" ]
        ]
      , div [ A.class "modal-back" ]
        [ form [ A.class "modal join-modal" ]
          [ label [ A.class "input-wrapper" ]
            [ span [ A.class "label" ]
              [ text "Passphrase" ]
            , div [ A.class "input" ]
              [ input [ A.name "password", A.placeholder "hunter2", A.attribute "required" "", A.type_ "text" ]
                []
              ]
            ]
          , input [ A.class "button submit-btn", A.type_ "submit", A.value "Join" ]
            []
          ]
        ]
      , p [ A.class "profile-desc" ]
        [ text "Please pick up the bowling balls from the front office by February 30th. Eliminations may only occur when the student is not carrying their bowling ball. Eliminations may not occur inside classes. Inappropriate behaviour will result in immediate disqualification. Targets will be shuffled every week. Good luck, Pizzas!" ]
      , p [ A.class "profile-desc profile-stats" ]
        [ text "Ongoing · 3 of 6 participants alive" ]
      ]
    , div [ A.class "lists" ]
      [ section [ A.class "list" ]
        [ h2 []
          [ text "Participants (6)" ]
        , a [ A.class "item", A.href "./user.html" ]
          [ span [ A.class "item-name" ]
            [ text "Jame Sooth" ]
          , span [ A.class "item-info" ]
            [ text "Alive · 2 eliminations" ]
          ]
        , a [ A.class "item dead", A.href "./user.html" ]
          [ span [ A.class "item-name" ]
            [ text "Sergo Neristo" ]
          , span [ A.class "item-info" ]
            [ text "Eliminated · 1 eliminations" ]
          ]
        , a [ A.class "item", A.href "./user.html" ]
          [ span [ A.class "item-name" ]
            [ text "Ern Seth" ]
          , span [ A.class "item-info" ]
            [ text "Alive · 0 eliminations" ]
          ]
        , a [ A.class "item", A.href "./user.html" ]
          [ span [ A.class "item-name" ]
            [ text "Memphie Ratch" ]
          , span [ A.class "item-info" ]
            [ text "Alive · 0 eliminations" ]
          ]
        , a [ A.class "item dead", A.href "./user.html" ]
          [ span [ A.class "item-name" ]
            [ text "Eghten Siuvoulet" ]
          , span [ A.class "item-info" ]
            [ text "Eliminated · 0 eliminations" ]
          ]
        , a [ A.class "item dead", A.href "./user.html" ]
          [ span [ A.class "item-name" ]
            [ text "Zuck Ergostan" ]
          , span [ A.class "item-info" ]
            [ text "Eliminated · 0 eliminations" ]
          ]
        ]
      ]
    ]
  ]
