module Pages.GameSettings exposing (view)

import Html exposing (..)
import Html.Attributes as A

view : List (Html msg)
view =
  [ div [ A.class "main content settings" ]
    [ h1 []
      [ text "Game settings"
      , span [ A.class "flex" ]
        []
      , button [ A.class "button", A.attribute "disabled" "" ]
        [ text "Start game" ]
      , a [ A.class "button", A.href "./game.html" ]
        [ text "View game page" ]
      ]
    , form []
      [ div [ A.class "input-row" ]
        [ label [ A.class "input-wrapper" ]
          [ span [ A.class "label" ]
            [ text "Name" ]
          , div [ A.class "input" ]
            [ input [ A.name "name", A.placeholder "The People's Elimination Game", A.attribute "required" "", A.type_ "text", A.value "Pistolita High School Elimination 2020" ]
              []
            , span [ A.class "count" ]
              [ text "13/50" ]
            ]
          ]
        , label [ A.class "input-wrapper" ]
          [ span [ A.class "label" ]
            [ text "Passphrase to join" ]
          , div [ A.class "input" ]
            [ input [ A.name "password", A.placeholder "hunter2", A.attribute "required" "", A.type_ "text", A.value "pistolitaelimination2020" ]
              []
            ]
          , span [ A.class "sublabel" ]
            [ text "Share this passphrase to people who you want to join." ]
          ]
        ]
      , div [ A.class "input-row" ]
        [ label [ A.class "input-wrapper" ]
          [ span [ A.class "label" ]
            [ text "Description and rules" ]
          , div [ A.class "input" ]
            [ textarea [ A.name "description", A.placeholder "", A.attribute "required" "" ]
              [ text "Please pick up the bowling balls from the front office by February 30th. Eliminations may only occur when the student is not carrying their bowling ball. Eliminations may not occur inside classes. Inappropriate behaviour will result in immediate disqualification. Targets will be shuffled every week. Good luck, Pizzas!" ]
            , span [ A.class "count" ]
              [ text "11/1000" ]
            ]
          , span [ A.class "sublabel" ]
            [ text "List rules for elimination here, such as how they can be blocked, and when and where eliminations are allowed to be made." ]
          ]
        ]
      , input [ A.class "button submit-btn", A.attribute "disabled" "", A.type_ "submit", A.value "Save" ]
        []
      ]
    , div [ A.class "members" ]
      [ h2 [ A.class "members-header" ]
        [ text "Participants (6)"
        , span [ A.class "flex" ]
          []
        , button [ A.class "button" ]
          [ text "Shuffle targets" ]
        ]
      , div [ A.class "member-item" ]
        [ div [ A.class "member" ]
          [ a [ A.class "link member-link", A.href "./user.html" ]
            [ text "Ern Seth" ]
          , span [ A.class "member-info" ]
            [ text "Joined 2020-01-23 · 0 eliminations" ]
          ]
        , button [ A.class "button kick-btn" ]
          [ text "Kick" ]
        , div [ A.class "modal-back" ]
          [ form [ A.class "modal join-modal" ]
            [ label [ A.class "input-wrapper" ]
              [ span [ A.class "label" ]
                [ text "Kick reason (optional)" ]
              , div [ A.class "input" ]
                [ input [ A.name "reason", A.placeholder "Undesirable.", A.type_ "text" ]
                  []
                ]
              ]
            , input [ A.class "button submit-btn", A.type_ "submit", A.value "Kick" ]
              []
            ]
          ]
        ]
      , div [ A.class "member-item" ]
        [ div [ A.class "member" ]
          [ a [ A.class "link member-link", A.href "./user.html" ]
            [ text "Sergo Neristo" ]
          , span [ A.class "member-info" ]
            [ text "Joined 2020-01-23 · 1 eliminations" ]
          ]
        , button [ A.class "button kick-btn" ]
          [ text "Kick" ]
        , div [ A.class "modal-back" ]
          [ form [ A.class "modal join-modal" ]
            [ label [ A.class "input-wrapper" ]
              [ span [ A.class "label" ]
                [ text "Kick reason (optional)" ]
              , div [ A.class "input" ]
                [ input [ A.name "reason", A.placeholder "Undesirable.", A.type_ "text" ]
                  []
                ]
              ]
            , input [ A.class "button submit-btn", A.type_ "submit", A.value "Kick" ]
              []
            ]
          ]
        ]
      , div [ A.class "member-item" ]
        [ div [ A.class "member" ]
          [ a [ A.class "link member-link", A.href "./user.html" ]
            [ text "Jame Sooth" ]
          , span [ A.class "member-info" ]
            [ text "Joined 2020-01-22 · 2 eliminations" ]
          ]
        , button [ A.class "button kick-btn" ]
          [ text "Kick" ]
        , div [ A.class "modal-back" ]
          [ form [ A.class "modal join-modal" ]
            [ label [ A.class "input-wrapper" ]
              [ span [ A.class "label" ]
                [ text "Kick reason (optional)" ]
              , div [ A.class "input" ]
                [ input [ A.name "reason", A.placeholder "Undesirable.", A.type_ "text" ]
                  []
                ]
              ]
            , input [ A.class "button submit-btn", A.type_ "submit", A.value "Kick" ]
              []
            ]
          ]
        ]
      , div [ A.class "member-item" ]
        [ div [ A.class "member" ]
          [ a [ A.class "link member-link", A.href "./user.html" ]
            [ text "Eghten Siuvoulet" ]
          , span [ A.class "member-info" ]
            [ text "Joined 2020-01-21 · 0 eliminations" ]
          ]
        , button [ A.class "button kick-btn" ]
          [ text "Kick" ]
        , div [ A.class "modal-back" ]
          [ form [ A.class "modal join-modal" ]
            [ label [ A.class "input-wrapper" ]
              [ span [ A.class "label" ]
                [ text "Kick reason (optional)" ]
              , div [ A.class "input" ]
                [ input [ A.name "reason", A.placeholder "Undesirable.", A.type_ "text" ]
                  []
                ]
              ]
            , input [ A.class "button submit-btn", A.type_ "submit", A.value "Kick" ]
              []
            ]
          ]
        ]
      , div [ A.class "member-item" ]
        [ div [ A.class "member" ]
          [ a [ A.class "link member-link", A.href "./user.html" ]
            [ text "Zuck Ergostan" ]
          , span [ A.class "member-info" ]
            [ text "Joined 2020-01-19 · 0 eliminations" ]
          ]
        , button [ A.class "button kick-btn" ]
          [ text "Kick" ]
        , div [ A.class "modal-back" ]
          [ form [ A.class "modal join-modal" ]
            [ label [ A.class "input-wrapper" ]
              [ span [ A.class "label" ]
                [ text "Kick reason (optional)" ]
              , div [ A.class "input" ]
                [ input [ A.name "reason", A.placeholder "Undesirable.", A.type_ "text" ]
                  []
                ]
              ]
            , input [ A.class "button submit-btn", A.type_ "submit", A.value "Kick" ]
              []
            ]
          ]
        ]
      , div [ A.class "member-item" ]
        [ div [ A.class "member" ]
          [ a [ A.class "link member-link", A.href "./user.html" ]
            [ text "Memphie Ratch" ]
          , span [ A.class "member-info" ]
            [ text "Joined 2020-01-15 · 0 eliminations" ]
          ]
        , button [ A.class "button kick-btn" ]
          [ text "Kick" ]
        , div [ A.class "modal-back" ]
          [ form [ A.class "modal join-modal" ]
            [ label [ A.class "input-wrapper" ]
              [ span [ A.class "label" ]
                [ text "Kick reason (optional)" ]
              , div [ A.class "input" ]
                [ input [ A.name "reason", A.placeholder "Undesirable.", A.type_ "text" ]
                  []
                ]
              ]
            , input [ A.class "button submit-btn", A.type_ "submit", A.value "Kick" ]
              []
            ]
          ]
        ]
      ]
    ]
  ]
